### PR TITLE
Addition and correction of French translation.

### PR DESCRIPTION
**Pull request by Ordissimo**
https://github.com/kiwix/kiwix-desktop/pull/25#issuecomment-509377368

### CODE REVIEW

**Comment by LAfricain** [comment]
There are some part not localised in the library by instance. It is possible that it is in the other dep to do it?

**Comment by kelson42** [comment]
@LAfricain Yes, could you please translate things on Translatewiki http://translate.kiwix.org

**Comment by LAfricain** [comment]
Nothing to be translated on Translatewiki

**Comment by kelson42** [comment]
@LAfricain Give me a few days please, I will try to sort out things.

**Comment by kelson42** [comment]
Merging and will migrate strings to translatewiki.net soon myself.

**Comment by LAfricain** [comment]
Despite this merge the current version of kiwix have still errors (corrected in the pull request) in the strings.

**Comment by LAfricain** [comment]
Why the last version has still errors in French or strings not translated?

**Comment by kelson42** [comment]
@LAfricain Because of #299

**Comment by LAfricain** [comment]
>Because of #299

I don't understand the link :) But it doesn't matter if you are working on it ;) Maybe for the 2.0.1 release the new strings will be ok?

**Pull request merged**
