### PR TITLE
remove category wikispecies

### LINKED ISSUE #113: wikispecies category filtering fails
I get no result

### PR DESCRIPTION
**Pull request by jetownfeve21**
fix #113

### CODE REVIEW

**Comment by kelson42** [comment]
@jetownfeve21 The ticket ask to remove "Wikispecies" nothing else. The other one should display multiple content. The problem here is why it does not!

**Comment by jetownfeve21** [comment]
You asked me to remove Wikispecies because it displays nothing, this is due to a wrong tag assignment, and the others that I removed are in the same case. I don't know how the tags are assigned

**Comment by kelson42** [comment]
@jetownfeve21 The main reason to remove the Wikispecies category is not because this is empty (this is a bug) but because even if it would work it would display only one content... so better leave it in the "Other" category. For the the other category you have removed in this PR, this is not the case, they should be kept and display multiple items. The question is why not? What do you mean exactly with "wrong tag assignment"? Do the ZIM metadata are wrong? If "yes" how are they wrong?

**Comment by jetownfeve21** [comment]
Gutenberg has only one content and there is no tags to clearly identify it as a gutenberg content
image

**Comment by jetownfeve21** [comment]
Same for the phet category, there is no tags at all
image

**Comment by jetownfeve21** [comment]
Ted has content but the files don't have tags
image

**Comment by jetownfeve21** [comment]
No tags for wikibooks
image

**Comment by jetownfeve21** [comment]
Wikispecies content have the tag "wikimedia"
image

**Comment by mgautierfr** [comment]
I'm partisan to fix the tags on the zim files. Here we are just adding special case in the client to fix bugs in another that our projects.
I prefer to create a small tool changing the tags in zim files instead of adding hacks in the client.

**Comment by mgautierfr** [comment]
@kelson42 This PR just remove wikispecies category.
Other categories are keep even if they return no result.
Are we agree ? If yes, feel free to merge it :)

**Pull request merged**
