### PR TITLE
Implement settings page

### PR DESCRIPTION
**Pull request by jetownfeve21**
@mgautierfr does this implementation seem correct to you ?
It's the same architecture as the contentmanager page but I recreate and delete the view each time

### CODE REVIEW

**Comment by jetownfeve21** [comment]
needs https://github.com/kiwix/kiwix-lib/pull/290 to work

**Comment by kelson42** [comment]
Crash scenario:
* Dispaly "Settings" tab
* Click on "library" tab
* Click back to "Settings" tab

**Comment by kelson42** [comment]
@jetownfeve21 Why this is implemented as a tab whereas the UI design says it should be a dialog?

**Comment by jetownfeve21** [comment]
@kelson42 I was using this design as a reference https://wikimedia.invisionapp.com/share/7UIVNGPS9CA#/screens/303981034

**Comment by kelson42** [comment]
@jetownfeve21 I was sure I had seen the settings as a dialog, sorry. My bad.

**Pull request merged**
