### PR TITLE
Handling of NoEntry in KiwixApp::openRandomUrl()

### LINKED ISSUE #742: Random generated exception 'kiwix:noentry" makes the app crashing
Clicking many times on random generates a crash:
```
 ./kiwix-desktop /tmp/ted_en_playlist-a-day-trip-to-antarctica_2021-01.zim 
Compiled with Qt Version  5.12.8
Runtime Qt Version  5.12.8
add widget
terminate called after throwing an instance of 'kiwix::NoEntry'
  what():  std::exception
Aborted (core dumped)
```

The bug is pretty proeminent because of https://github.com/kiwix/libkiwix/issues/643

### PR DESCRIPTION
**Pull request by veloman-yunkan**
Fixes #742

Now a message box is shown in case of an exception.

### CODE REVIEW

**Comment by kelson42** [comment]
I guess this message can not be translated... and it ahoukd probably be. It should be introduced beside the other strings in the English localisation file.

**Comment by veloman-yunkan** [comment]
> I guess this message can not be translated... and it ahoukd probably be. It should be introduced beside the other strings in the English localisation file.

@kelson42 Done. I also added a Russian translation of the new error in order to make sure that it works. Will the other translations be generated automatically (by translatewiki.net) later?

**Comment by kelson42** [comment]
@veloman-yunkan Thank you. Yes, twice a week english is uploaded upstream on TW and other languages are downloaded from TW and a dedicated PR is done.

**Review by kelson42 — APPROVED** [review]
Thx!

**Pull request merged**
