### PR TITLE
Possible implementation for "Not enough space storage" message.

### LINKED ISSUE #959: Give more information about the "Not enough space storage" message.
Having more information like:
- Needed space,
- Available space,
- Destination directory

would be useful.

### PR DESCRIPTION
**Pull request by franklinthai**
Fixes #959

Added more error message output including target directory and space available.

### CODE REVIEW

**Review by mgautierfr — CHANGES_REQUESTED** [review]
Thanks for you PR.

However, your PR doesn't handle translation.
You have to extend at least https://github.com/kiwix/kiwix-desktop/blob/main/resources/i18n/en.json to update or add new strings (and potatially update https://github.com/kiwix/kiwix-desktop/blob/main/resources/i18n/qqq.json to give information to translators about the string to translate).

And then, insert the values in the string before displaying it (as a example, this is done this way here https://github.com/kiwix/kiwix-desktop/blob/75ecdeb03e89d6a5dcaae89109bab8f0b43d1a39/src/contentmanager.cpp#L667-L668)

**Comment by kelson42** [comment]
@franklinthai Any feedback?

**Comment by franklinthai** [comment]
I have not been able to fix this yet. I'll try to get on it in the next few days.

**Comment by franklinthai** [comment]
Hello, sorry for being assigned this issue for so long and not being able to finish it.

**Pull request closed without merging**
