### PR TITLE
Single application kiwix-desktop

### LINKED ISSUE #147: Two Kiwix-Desktop instances can be run in parallel
I don't think this is really something we want... or we should guaranty that everything will works fine. Is that the case? A Singleton Windows seems more appropriate.

### PR DESCRIPTION
**Pull request by jetownfeve21**
fix #147

### CODE REVIEW

**Comment by jetownfeve21** [comment]
@mgautierfr not sure if the qt solution is installation is correct like that

**Comment by jetownfeve21** [comment]
https://code.qt.io/cgit/qt-solutions/qt-solutions.git/tree/qtsingleapplication/INSTALL.TXT
In the INSTALL.TXT, they recommend to use it as a library but we can compile the sources directly too

**Comment by kelson42** [comment]
@mgautierfr @jetownfeve21 Could we please move on this PR?

**Comment by mgautierfr** [comment]
> In the INSTALL.TXT, they recommend to use it as a library but we can compile the sources directly too

They said it is preferable for licensing issue, but we don't have this problem. The singleappliaction base app is bsd, we can use it in a gpl project.

On the opposite side, we need to have binaries for linux and windows (and potentially with different versions). And there is no dll in the PR. It would be preferable to compile the code all the time and use it directly (without intermediate dll/so).

**Comment by jetownfeve21** [comment]
> On the opposite side, we need to have binaries for linux and windows (and potentially with different versions). And there is no dll in the PR. It would be preferable to compile the code all the time and use it directly (without intermediate dll/so).

That's true, it compiles the code all the the time now

**Comment by mgautierfr** [comment]
Have you tested it on windows ? (I haven't)

**Comment by mgautierfr** [comment]
Then we are good.

**Pull request merged**
