### PR TITLE
Added condition to zoom in/out only for the current tab

### LINKED ISSUE #654: Zoom in/out/reset shoold work forthe current tab only
Currently (57162a79) Zoom in/out/reset action applied to all the opened tabs.

## Actual result

Pressing Ctrl++  Ctrl+-  (or zoom in/out with mouse wheel) is applied to every opened tab at the moment.

## Expected result

Pressing Ctrl++  Ctrl+-  (or zoom in/out with mouse wheel) should be applied to the current (active) tab only, as it is in all major web browsers.

## Additional details

In code that happens because Zoom in/out/reset is connected to every tab object created, regardless of the current tab:

https://github.com/kiwix/kiwix-desktop/blob/57162a79ed21b46a65622093aa12cf5d99738cff/src/zimview.cpp#L21

Suggested solution:

Handle Zoom in/out/reset like we handle 'Print' command (only the currently active tab is printed):

https://github.com/kiwix/kiwix-desktop/blob/57162a79ed21b46a65622093aa12cf5d99738cff/src/kiwixapp.cpp#L305

https://github.com/kiwix/kiwix-desktop/blob/57162a79ed21b46a65622093aa12cf5d99738cff/src/kiwixapp.cpp#L184

### PR DESCRIPTION
**Pull request by juuz0**
Fixes #654

### CODE REVIEW

**Comment by kelson42** [comment]
@juuz0 Thx for the quick fix. Thx as well for accepting the invitation to join the team and put your feature branch in our repo. That should - at least - ease rebase operations.

**Comment by juuz0** [comment]
@kelson42 I haven't done that previously so not sure, should I push this feature branch onto the main kiwix-desktop repo? and then should I make up a new PR?

**Comment by kelson42** [comment]
@juuz0 Oh, sorry I see you still have it in your fork. You shoukd create a branch in the repo (not in your branch) and push your commit there. Then create a new PR.

**Comment by juuz0** [comment]
Okay then I should close this one, i guess?

**Comment by kelson42** [comment]
Superseeded by #689

**Pull request closed without merging**
