### PR TITLE
Fix Back & Forward button alignment for -reverse launch

### LINKED ISSUE #595: Wrong order of Back / Forward buttons in right-to-left layout
Found on current 'master' (ca776b46)

### Steps to reproduce:

1. Run Kiwix application with right-to-left interface layout by adding -reverse CLI option
2. See to Back / Forward buttons in the toolbar

### Actual result:

Screenshot from 2021-02-13 00-08-33

### Expected result:

Back / Forward buttons should be mirrored. So Back goes the first on the right, Forward the second.

### Additional information

There is separated issue on how the other buttons drawn: #594

### PR DESCRIPTION
**Pull request by juuz0**
Fixes #595

### CODE REVIEW

**Comment by kelson42** [comment]
@juuz0 Actually I'm not really sure about how to test this as there is no settings to change UI language. Any hint on your side?

**Comment by juuz0** [comment]
@kelson42 yes, start kiwix desktop from Terminal as 
`kiwix-desktop -reverse`

**Comment by kelson42** [comment]
@juuz0 I have, I hope so, improved a bit the situation on the top of your commit. What do you think about it?

**Comment by juuz0** [comment]
@kelson42 LGTM!

**Comment by kelson42** [comment]
@mgautierfr Looks good to you too?

**Review by mgautierfr — APPROVED** [review]
LGTM too

**Pull request merged**
