### PR TITLE
Localisation updates from https://translatewiki.net.

### PR DESCRIPTION
**Pull request by translatewiki**
Translation updates

### CODE REVIEW

**Comment by kelson42** [comment]
@legoktm Do you know why the whole packaging CI fails on that one? The compilation on my machine workd fine.

**Comment by legoktm** [comment]
I noticed https://github.com/kiwix/kiwix-lib/pull/419 in the logs, I'm not totally sure that's the whole error though.

**Comment by legoktm** [comment]
OK, I tested it locally and it fails without the libmicrohttpd-dev patch and works with it. So that PR should unblock this one.

**Comment by kelson42** [comment]
@legoktm @mgautierfr Unfortunately still failing, even after your fix in libkiwix @legoktm :(

**Comment by legoktm** [comment]
Looks like the same problem as zim-tools, the updated libkiwix hadn't made it to the PPA yet. Jobs are passing now!

**Pull request merged**
