### PR TITLE
Fix menu in fullscreen on Windows

### LINKED ISSUE #305: On Windows menu is not visible if in fullscreen
Steps to reproduce:
* Get the rc3 for Windows
* Launch Kiwix Desktop for Windows
* Click on the Fullscreen icon (or F11)
* Click on the 3-dots icon
* Nothing happens

I should see the corresponding menu appearing. If I leave the fullscreen mode, then it works again.

### PR DESCRIPTION
**Pull request by jetownfeve21**
fix #305

### CODE REVIEW

**Comment by kelson42** [comment]
@jetownfeve21 What is this PR, what should we do with it?

**Comment by rahulps108** [comment]
menus dont show up in full screen

**Comment by kelson42** [comment]
@jetownfeve21 What is the status here? What should we do with this PR?

**Comment by jetownfeve21** [comment]
@kelson42 I'm still working on it, I was waiting for the appveyor compilation to be fixed

**Comment by kelson42** [comment]
@jetownfeve21 So, this compilation is fixed now, you confirm?

**Pull request merged**
