### PR TITLE
Disable random article in settings view

### LINKED ISSUE #954: Random icon must be greyed if settings open
image

### PR DESCRIPTION
**Pull request by juuz0**
Fixes #954

### CODE REVIEW

**Review by veloman-yunkan — COMMENTED** [review]
A more proper fix seems to be the following:

1. change the type of the parameter of `KiwixApp::disableItemsOnLibraryPage(bool libraryDisplayed)` and `TabBar::libraryPageDisplayed(bool displayed)`
from `bool` to a new enum type which tells the kind of the current tab (content, library, settings). Inside that function enable only actions that make sense for the current tab kind.
2. Naturally after that change `KiwixApp::disableItemsOnLibraryPage()` and `TabBar::libraryPageDisplayed(bool displayed)` have to be renamed.

**Comment by mgautierfr** [comment]
Agree with @veloman-yunkan, those functions have been created when there was no setting page. Now we have more than 2 kinds of tab, we should create more generic functions to handle "action configuration" when we change tabs.

**Comment by kelson42** [comment]
@juuz0 Ready for a new review?

**Comment by juuz0** [comment]
@kelson42 yes

**Review by veloman-yunkan — APPROVED** [review]

**Pull request merged**
