### PR TITLE
Fix CloseTab related weakness

### LINKED ISSUE #968: Shortcuts `ctrl+f4` and `ctrl+w` should close current tab
The shortcut `ctrl + f4` only works immediately after a tab has been clicked. What I expect is that that shortcut always closes the current tab regardless of what has been clicked or what is in focus like in any other browser e.g. chrome or firefox. Furthermore, any other browser support `ctrl + w` along with `ctrl + f4` to close the current tab.

Additional suggestion: Add `ctrl + w` to close the current tab.

Currently, I tested this issue on kiwix-desktop 2.3.1 on both windows 7 and 10.

### PR DESCRIPTION
**Pull request by juuz0**
Fixes #968

### CODE REVIEW

**Comment by kelson42** [comment]
@juuz0 IMO, it shpuld mot be "in place", but "in addition".

**Comment by juuz0** [comment]
>  IMO, it should mot be "in place", but "in addition".

 Do you mean the shortcuts?
Sadly if I use `QKeySequence::close` in addition to these two, QT consider that an ambiguity so i explicitly mentioned both shortcuts.

**Review by kelson42 — APPROVED** [review]
Seems to work properly now and principle LGTM. I would still put a comment explaining about the usage of `CREATE_ACTION_ICON_SHORTCUTS` why we don't use anymore `QKeySequence::Close`.

**Review by mgautierfr — APPROVED** [review]

**Comment by mgautierfr** [comment]
>  why we don't use anymore QKeySequence::Close.

This is explain in the commit message.

**Pull request merged**
