### PR TITLE
Add Flatpak build files.

### LINKED ISSUE #2: Make a flatpack package

### PR DESCRIPTION
**Pull request by birros**
I hope this will be useful ;)

If you have any questions, don't hesitate.

P.S. : Glad to see your new baby ;)

This fix #2

### CODE REVIEW

**Comment by kelson42** [comment]
@birros Thank you for your PR. Nice to hear again from you :) We are quite busy these weeks, but we want to go ahead with flatpack and you PR will be taken in consideration. Please bit just a bit patient with the treatment of it.

**Comment by mgautierfr** [comment]
Thanks @birros , It is definitively useful :)
Independently of the content of the PR itself, I wonder if it could be better merged in `kiwix-build` instead of `kiwix-desktop`.

As you said, only `org.kiwix.Client.yml` is needed to build the flatpack, flatpack-builder downloading the sources itself.
It is somehow what we do in `kiwix-build`, we download and build all the dependencies of our project.

More over, as we make reference to dependencies url/version in `org.kiwix.Client.yml`, it would be also better to push it in `kiwix-build` to simplify synchronization of dependency update as we already track dependencies there.

Can you create the PR there ? (Except if you have arguments to keep it here)

BTW, Except few cosmetics remarks I will made on the PR on kiwix-build I have tested the PR and it works very well !

**Comment by birros** [comment]
Thanks for your interest :-)

I posted this pull request here because I don't know how you want to integrate it. In fact, it depends on how you want to deploy your flatpak.

From what I see, two methods concern you:

1. **Build a flatpak file** to download it directly from your site
2. **Deploy kiwix-desktop to Flathub**, the application store that is the *official repo* in the Flatpak world

Both methods are based on a manifest, here `org.kiwix.Client.yml`, which is relatively easy to create using the dependency system defined in `kiwix-build`. The idea would be to use this information and a template to produce it.

## To Build The flatpak File Locally

In this case the instructions I give in the `README` to build a bundle are fine. This would require creating a script like the one used to build an AppImage.

## To Deploy To Flathub

This is where things get a little complicated since there is nothing to build locally, the app is built and deployed automatically based on the manifest that is present in a dedicated repo under the organisation https://github.com/flathub. The documentation is rather complete and explicit:

- https://github.com/flathub/flathub/wiki/App-Submission
- https://github.com/flathub/flathub/wiki/App-Maintenance

---

I'm ready to try integrating this into `kiwix-build` but I'm a little lost in its architecture. I need some clarifications on the procedure to follow ;-)

**Comment by trappedinspacetime** [comment]
I've tried it, `kiwix-lib-2.0.2` fails to build. It also needs network access to launch application.

**Comment by kelson42** [comment]
@birros Your code, tuned by @mgautierfr has been merged to kiwix-build https://github.com/kiwix/kiwix-build. It works fine and we have nightly built flatpack packages of Kiwix Desktop, see for example: https://download.kiwix.org/nightly/2018-12-23/. Now we are working to publish it automatically on Flathub, see #281. Thank you again for the help on this.

**Comment by kelson42** [comment]
@trappedinspacetime Please open a ticket on kiwix-build repo with the detailed step-by-step procedure you follow, the result you get and the result you expect.

**Pull request closed without merging**
