### PR TITLE
Make app icon correctly scalable on Windows

### LINKED ISSUE #1153: Icon is distorded
On Windows 11, the app's icon, either in Explorer or in the taskbar is distorded. Other icons are OK.

Screenshot 2024-07-26 at 11 23 05

Screenshot 2024-07-26 at 11 23 16

### PR DESCRIPTION
**Pull request by sgourdas**
This aims to allow for the app_icon.ico to properly render on Windows and not stretch by resizing it to 256x256 and filling the gap with transparency.

Fixes #1153

### CODE REVIEW

**Comment by kelson42** [comment]
@sgourdas How this version is different from the previous one?

**Comment by sgourdas** [comment]
@kelson42 I tested by setting the new icon as a folder icon in Windows.

Seems to be correct now:
image

**Comment by sgourdas** [comment]
@kelson42 I resized the icon in square dimensions so it scales correctly

**Comment by kelson42** [comment]
@sgourdas Thank you for your quick fix!

**Pull request merged**
