### PR TITLE
Do not delete zim file from fs when we delete book from the library.

### LINKED ISSUE #479: Deleting a ZIM file should move it to the trash can
When I delete a ZIM file from the library, it is also deleted from the hard disk at the same time! And the basket remains empty!
**Ubuntu 18.04 Unity** + **Kiwix 2.0.1-1** (*.appimage):
Kiwix-deleting-ZIM

The situation is exactly the same in the operating system **Ubuntu 18.04 MATE** + **Kiwix 2.0.1-1** (*.appimage).

### PR DESCRIPTION
**Pull request by mgautierfr**
Fix #479

### CODE REVIEW

**Comment by kelson42** [comment]
@mgautierfr what does this PR exactly?

**Comment by mgautierfr** [comment]
> what does this PR exactly? 

With this PR, when a user remove a book in kiwix-desktop, the book is removed from the library but the zim file is not deleted from file system. Instead, we display a message saying the file(s) has not been deleted and telling the path where to find the zim files.

> IMO the way it works on iOS is the proper way.

I don't know how iOS is working :)

**Comment by kelson42** [comment]
@mgautierfr I think you mean this PR should fix https://github.com/kiwix/kiwix-desktop/issues/517... an I have put there what I expect for a solution

**Comment by kelson42** [comment]
Superseeded by #531

**Pull request closed without merging**
