### PR TITLE
Eliminated emit of Library class signals from other objects

### LINKED ISSUE #540: Codebase: emiting a signal forcedly from outside is a bad practice
kiwix-desktop 'master' (830e19bb)

Found during working on #454

From src/zimview.cpp:
```c
emit mp_tabBar->currentTitleChanged(str);
emit mp_tabBar->currentZimIdChanged(zimId);
emit mp_tabBar->webActionEnabledChanged(QWebEnginePage::Back, mp_webView->isWebActionEnabled(QWebEnginePage::Back));
emit mp_tabBar->webActionEnabledChanged(QWebEnginePage::Forward, mp_webView->isWebActionEnabled(QWebEnginePage::Forward));
emit mp_library->bookmarksChanged();
```

According to Qt documentation, this is a bad practice.
By signals, only the object itself should notify that its internal state has changed:

https://doc.qt.io/qt-5/signalsandslots.html

> Signals
> Signals are emitted by an object when its internal state has changed in some way that might be interesting to the object's client or owner. Signals are public access functions and can be emitted from anywhere, but we recommend to only emit them from the class that defines the signal and its subclasses.

### PR DESCRIPTION
**Pull request by ShaopengLin**
Fix #540

Change:
 - Created member function in Library class to emit signals
 - Other classes simply use these if they would like to emit such signals.

### CODE REVIEW

**Comment by ShaopengLin** [comment]
Though the original issue mentions we can connect signals to signals, here I think just using a member function does the job. For this particular case, creating different signals in different classes just for this purpose feels redundant.

**Review by veloman-yunkan — COMMENTED** [review]
I don't think that these changes are an improvement - the new member functions are no different from the signal being emitted explicitly.

**Comment by ShaopengLin** [comment]
The purpose is to emit signals within the object, which I believe member function would be doing that? For the LibraryManipulator, we cannot inherit QObject so we have to rely on a direct emission or member function of some sort.

Both creating extra signals and creating member methods are hacks, but they should do the job. @asashnov Do you have an input on whether we should stick to connecting signals as much as possible or is using member function calls fine.

**Comment by veloman-yunkan** [comment]
> The purpose is to emit signals within the object

But doing it via a dedicated member function doesn't make the design better. I guess the design principle is that the objects should emit signals from within otherwise meaningful methods.

**Comment by ShaopengLin** [comment]
Yeah that is good overall principle, I will refactor this.

**Review by veloman-yunkan — COMMENTED** [review]
I can't justify merging these changes as well as continuing the work on this PR. To me it looks like applying a minute amount of Dior fragrance to an athlete after extensive workout before he takes shower and changes his clothes. I believe that the mild issue being addressed should rather be fixed as a by-product of a more serious refactoring/redesign/code-cleanup.

**Comment by kelson42** [comment]
> I can't justify merging these changes as well as continuing the work on this PR. To me it looks like applying a minute amount of Dior fragrance to an athlete after extensive workout before he takes shower and changes his clothes. I believe that the mild issue being addressed should rather be fixed as a by-product of a more serious refactoring/redesign/code-cleanup.

I can agree with that, but then please try to phrase the nature of the problem (and maybe a bit of the solution) within an issue. I understand that this might be a bit challenging, and if too complicated/touchy we won't give it to a student.

**Comment by veloman-yunkan** [comment]
@kelson42 Let's not waste time on bureaucracy around a minor issue. Just assign it to me and I will resolve it over time as I rewrite more of `kiwix-desktop`'s source code.

**Pull request closed without merging**
