### PR TITLE
bigger menu icon

### LINKED ISSUE #281: Menu logos should be bigger
They are almost twice to small in comparison to the UI design mockups

Here is an example I have taken with the "Settings" menu entry. The first one is the UI design mockup, the second is issue from a screenshot I have made of my Kiwix Desktop.

image

### PR DESCRIPTION
**Pull request by jetownfeve21**
apply a custom proxystyle for the menu widget to change the icon size

fix #281

### CODE REVIEW

**Comment by kelson42** [comment]
@jetownfeve21 Any news on that one? The solution looks more like a workaround to me.

**Comment by jetownfeve21** [comment]
@kelson42 It seems that the overlapping problem of the appimage comes from the Qt version that the appimage uses which is Qt 5.9

**Comment by kelson42** [comment]
I use Qt 5.9.
```
$ qmake --version
QMake version 3.1
Using Qt version 5.9.5 in /usr/lib/x86_64-linux-gnu
```

@mgautierfr @jetownfeve21 Same as #176 ?

**Comment by mgautierfr** [comment]
Yes, We have to move to a more recent version of Qt. See kiwix/kiwix-build#403

**Comment by kelson42** [comment]
@jetownfeve21 Then, I will review again your PR and if OK (beside this) I will merge it. Flatpak does already use 5.13 and Appveyor 5.12... so we should not be strongly impacted. The problem with appimage is well known and I don't want to stop things because of it.

**Comment by mgautierfr** [comment]
> Flatpak does already use 5.13

No, it use 5.12

**Comment by kelson42** [comment]
@jetownfeve21 Surprisingly it displays now properly here on my machine. Looks really better. Was worth the effort.

**Pull request merged**
