### PR TITLE
Sort books

### LINKED ISSUE #139: Sort by name, date, content type, size
Add the possibility to sort books by clicking on the column's header.

image

### PR DESCRIPTION
**Pull request by jetownfeve21**
fixes #139

### CODE REVIEW

**Comment by kelson42** [comment]
@mgautierfr Can we please have this PR reviewed/merged?

**Comment by mgautierfr** [comment]
> @mgautierfr Can we please have this PR reviewed/merged?

Please, the last push is 22 minutes ago...

**Comment by mgautierfr** [comment]
I have some doubt about the "reset sort" button styling.
Capture d’écran du 2019-06-27 17-46-43
If it is ok for you @kelson42 we can merge it.

**Comment by kelson42** [comment]
@mgautierfr Does not fix the UI mockup... but is not worse than the rest. So OK to me.

**Pull request merged**
