### PR TITLE
Fixed #544 : Crash on closing empty tab after Settings opened

### LINKED ISSUE #544: Crash on closing empty tab after Settings opened
Found on current 'master' (830e19bb)

## Steps to reproduce

1. Run the program
1. Open any file from library (it was 11 Gb EN Wikipedia in my case)
1. click + in tabbar to create an empty tab
1. From ... menu choose Settings to open Settings tab
1. Switch back to the opened file (Wikipedia in my case)
1. Again go to ... menu and choose Settings (nothing happens)
1. click X to close the empty tab (without switching into it before)

## Actual result

Application crashes

## Expected result

The empty tab should be silently closed, with no crash.

## Additional information

```
1  QWebEnginePage::action(QWebEnginePage::WebAction) const                                                                                                                                       0x7ffff77a6d41 
2  WebView::isWebActionEnabled                                                                                                                                            webview.cpp        28  0x55555559e60d 
3  TabBar::onCurrentChanged                                                                                                                                               tabbar.cpp         241 0x5555555b28ad 
4  QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<int>, void, void (TabBar:: *)(int)>::call                                                            qobjectdefs_impl.h 136 0x5555555b3f7f 
5  QtPrivate::FunctionPointer<void (TabBar:: *)(int)>::call<QtPrivate::List<int>, void>                                                                                   qobjectdefs_impl.h 169 0x5555555b3ead 
6  QtPrivate::QSlotObject<void (TabBar:: *)(int), QtPrivate::List<int>, void>::impl                                                                                       qobject_impl.h     120 0x5555555b3d3b 
7  QMetaObject::activate(QObject *, int, int, void * *)                                                                                                                                          0x7fffeeb15876 
8  QTabBar::currentChanged(int)                                                                                                                                                                  0x7ffff060d64e 
9  QTabBar::setCurrentIndex(int)                                                                                                                                                                 0x7ffff0611b0f 
10 TabBar::setSelectionBehaviorOnRemove                                                                                                                                   tabbar.cpp         225 0x5555555b263e 
11 TabBar::closeTab                                                                                                                                                       tabbar.cpp         211 0x5555555b256e 
12 TabBar::<lambda()>::operator()(void) const                                                                                                                             tabbar.cpp         66  0x5555555b1368 
13 QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, TabBar::TabBar(QWidget *)::<lambda()>>::call(TabBar::<lambda()> &, void * *)                 qobjectdefs_impl.h 130 0x5555555b3675 
14 QtPrivate::Functor<TabBar::TabBar(QWidget *)::<lambda()>, 0>::call<QtPrivate::List<>, void>(TabBar::<lambda()> &, void *, void * *)                                    qobjectdefs_impl.h 240 0x5555555b3408 
15 QtPrivate::QFunctorSlotObject<TabBar::TabBar(QWidget *)::<lambda()>, 0, QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase *, QObject *, void * *, bool *) qobject_impl.h     168 0x5555555b31f7 
16 QMetaObject::activate(QObject *, int, int, void * *)                                                                                                                                          0x7fffeeb15876 
17 QAction::triggered(bool)                                                                                                                                                                      0x7ffff0467782 
18 QAction::activate(QAction::ActionEvent)                                                                                                                                                       0x7ffff0469c20 
19 ??                                                                                                                                                                                            0x7ffff0561800 
20 QAbstractButton::mouseReleaseEvent(QMouseEvent *)                                                                                                                                             0x7ffff0561915 
21 QToolButton::mouseReleaseEvent(QMouseEvent *)                                                                                                                                                 0x7ffff063057a 
22 QWidget::event(QEvent *)                                                                                                                                                                      0x7ffff04a9b58 
23 QToolButton::event(QEvent *)                                                                                                                                                                  0x7ffff0630649 
24 QApplicationPrivate::notify_helper(QObject *, QEvent *)                                                                                                                                       0x7ffff046d70c 
25 QApplication::notify(QObject *, QEvent *)                                                                                                                                                     0x7ffff0475513 
26 QCoreApplication::notifyInternal2(QObject *, QEvent *)                                                                                                                                        0x7fffeeaeaf68 
27 QApplicationPrivate::sendMouseEvent(QWidget *, QMouseEvent *, QWidget *, QWidget *, QWidget * *, QPointer<QWidget>&, bool)                                                                    0x7ffff047417f 
28 ??                                                                                                                                                                                            0x7ffff04c3536 
29 ??                                                                                                                                                                                            0x7ffff04c5e8b 
30 QApplicationPrivate::notify_helper(QObject *, QEvent *)                                                                                                                                       0x7ffff046d70c 
31 QApplication::notify(QObject *, QEvent *)                                                                                                                                                     0x7ffff0474b37 
32 QCoreApplication::notifyInternal2(QObject *, QEvent *)                                                                                                                                        0x7fffeeaeaf68 
33 QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent *)                                                                                                        0x7fffefc97d40 
34 QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent *)                                                                                          0x7fffefc99b15 
35 QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>)                                                                                                         0x7fffefc7460b 
36 ??                                                                                                                                                                                            0x7fffdbb82010 
37 g_main_context_dispatch                                                                                                                                                                       0x7fffea9d4417 
38 ??                                                                                                                                                                                            0x7fffea9d4650 
39 g_main_context_iteration                                                                                                                                                                      0x7fffea9d46dc 
40 QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)                                                                                                                    0x7fffeeb3d86f 
41 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>)                                                                                                                                       0x7fffeeae955a 
42 QCoreApplication::exec()                                                                                                                                                                      0x7fffeeaf1e34 
43 main                                                                                                                                                                   main.cpp           36  0x555555589337 
```

### PR DESCRIPTION
**Pull request by rishabh-soni**
Just one little change was needed, the setSelectionBehaviorOnRemove() function was to be executed before comparing the index with m_settingsIndex. So I just shifted that line of code before the if conditions. This fixes the issue #544

### CODE REVIEW

**Comment by kelson42** [comment]
@rishabh-soni Thank you very much. In the future try to not work on a ticket which is already assigned. Or at least ask before in a comment.

**Comment by rishabh-soni** [comment]
So sorry didn't notice that it was already assigned. I will make sure that doesn't happen the next time.

**Comment by kelson42** [comment]
@asashnov We have a bit backlog of reviews to do because most of the team is focus on libzim 7.0.0 réease. Does this PR looks good to you?

**Comment by asashnov** [comment]
@kelson42 Sorry for the delay, didn't see the assignment.

@rishabh-soni Change looks good, but the commits history is dirty. Actually, you can:
* remove your local branch
* checkout a new one from 'master' with the same name
* make your commit
* git push 'with force' to overwrite your previous commits

**Review by asashnov — CHANGES_REQUESTED** [review]
need to clean commits history as described in:
https://github.com/kiwix/kiwix-desktop/pull/577#issuecomment-766821615

**Comment by rishabh-soni** [comment]
Okay, I'll do it by today 👍🏼

**Review by asashnov — APPROVED** [review]
Great, the commits history is clean now.  

But we may not need this change already because on the current 'master' at step 6. from  #544 report Settings tab is shown.

**Pull request merged**
