### PR TITLE
[WIP] remove reload action in context menu (not working)

### LINKED ISSUE #328: Remove "Reload" context menu
I don't see any value to it. Just make things more complex. I want to have it removed.

image

### PR DESCRIPTION
**Pull request by jetownfeve21**
fix #328

### CODE REVIEW

**Comment by jetownfeve21** [comment]
@mgautierfr I tried to do the same as in this [PR](https://github.com/kiwix/kiwix-desktop/pull/306/files) but don't understand why it doesn't work here

**Comment by mgautierfr** [comment]
> @mgautierfr I tried to do the same as in this PR but don't understand why it doesn't work here

Your PR is ok on my side. I have no reload button.

**Comment by jetownfeve21** [comment]
Another problem with a different behaviour on our computer, what should we do @kelson42 ?

**Comment by kelson42** [comment]
@jetownfeve21 Merge and we will see who is the exception.

**Pull request merged**
